import i18n from "@/lib/i18n";

export function alertingCopy() {
	return {
		rules: i18n.t("workspace.alerting.screenCopy.rules"),
		rulesDescription: i18n.t("workspace.alerting.screenCopy.rulesDescription"),
		channels: i18n.t("workspace.alerting.screenCopy.channels"),
		channelsDescription: i18n.t("workspace.alerting.screenCopy.channelsDescription"),
		history: i18n.t("workspace.alerting.screenCopy.history"),
		historyDescription: i18n.t("workspace.alerting.screenCopy.historyDescription"),
		privateWarning: i18n.t("workspace.alerting.screenCopy.privateWarning"),
		add: i18n.t("workspace.alerting.screenCopy.add"),
		save: i18n.t("workspace.alerting.screenCopy.save"),
		cancel: i18n.t("workspace.alerting.screenCopy.cancel"),
		delete: i18n.t("workspace.alerting.screenCopy.delete"),
		edit: i18n.t("workspace.alerting.screenCopy.edit"),
		test: i18n.t("workspace.alerting.screenCopy.test"),
		evaluate: i18n.t("workspace.alerting.screenCopy.evaluate"),
		noItems: i18n.t("workspace.alerting.screenCopy.noItems"),
		beta: i18n.t("workspace.alerting.screenCopy.beta"),
		name: i18n.t("workspace.alerting.screenCopy.name"),
		type: i18n.t("workspace.alerting.screenCopy.type"),
		status: i18n.t("workspace.alerting.screenCopy.status"),
		enabled: i18n.t("workspace.alerting.screenCopy.enabled"),
		disabled: i18n.t("workspace.alerting.screenCopy.disabled"),
		description: i18n.t("workspace.alerting.screenCopy.description"),
		webhookUrl: i18n.t("workspace.alerting.screenCopy.webhookUrl"),
		routingKey: i18n.t("workspace.alerting.screenCopy.routingKey"),
		headersJson: i18n.t("workspace.alerting.screenCopy.headersJson"),
		keepSecret: i18n.t("workspace.alerting.screenCopy.keepSecret"),
		channelSaved: i18n.t("workspace.alerting.screenCopy.channelSaved"),
		testSent: i18n.t("workspace.alerting.screenCopy.testSent"),
		scope: i18n.t("workspace.alerting.screenCopy.scope"),
		scopeId: i18n.t("workspace.alerting.screenCopy.scopeId"),
		provider: i18n.t("workspace.alerting.screenCopy.provider"),
		modelTarget: i18n.t("workspace.alerting.screenCopy.modelTarget"),
		budgetTarget: i18n.t("workspace.alerting.screenCopy.budgetTarget"),
		window: i18n.t("workspace.alerting.screenCopy.window"),
		minimumRequests: i18n.t("workspace.alerting.screenCopy.minimumRequests"),
		cooldown: i18n.t("workspace.alerting.screenCopy.cooldown"),
		notifyOnce: i18n.t("workspace.alerting.screenCopy.notifyOnce"),
		cel: i18n.t("workspace.alerting.screenCopy.cel"),
		celHelp: i18n.t("workspace.alerting.screenCopy.celHelp"),
		evaluateDescription: i18n.t("workspace.alerting.screenCopy.evaluateDescription"),
		ignoreCooldown: i18n.t("workspace.alerting.screenCopy.ignoreCooldown"),
		evaluateButton: i18n.t("workspace.alerting.screenCopy.evaluateButton"),
		ruleSaved: i18n.t("workspace.alerting.screenCopy.ruleSaved"),
		evaluationCompleted: i18n.t("workspace.alerting.screenCopy.evaluationCompleted"),
		evaluationResult: (matched: number, sent: number) =>
			i18n.t("workspace.alerting.screenCopy.evaluationResult", { value0: matched, value1: sent }),
		time: i18n.t("workspace.alerting.screenCopy.time"),
		rule: i18n.t("workspace.alerting.screenCopy.rule"),
		channel: i18n.t("workspace.alerting.screenCopy.channel"),
		deliveryDetails: i18n.t("workspace.alerting.screenCopy.deliveryDetails"),
		genericWebhook: i18n.t("workspace.alerting.screenCopy.genericWebhook"),
		allScopes: i18n.t("workspace.alerting.screenCopy.allScopes"),
		allChannels: i18n.t("workspace.alerting.screenCopy.allChannels"),
		scopeLabels: {
			provider: i18n.t("workspace.alerting.screenCopy.scopeLabels_provider"),
			virtual_key: i18n.t("workspace.alerting.screenCopy.scopeLabels_virtual_key"),
			team: i18n.t("workspace.alerting.screenCopy.scopeLabels_team"),
			customer: i18n.t("workspace.alerting.screenCopy.scopeLabels_customer"),
		},
		statusLabels: {
			all: i18n.t("workspace.alerting.screenCopy.statusLabels_all"),
			sent: i18n.t("workspace.alerting.screenCopy.statusLabels_sent"),
			failed: i18n.t("workspace.alerting.screenCopy.statusLabels_failed"),
			skipped: i18n.t("workspace.alerting.screenCopy.statusLabels_skipped"),
		},
		units: {
			minutes: i18n.t("workspace.alerting.screenCopy.units_minutes"),
			hours: i18n.t("workspace.alerting.screenCopy.units_hours"),
			days: i18n.t("workspace.alerting.screenCopy.units_days"),
		},
		detailsHidden: i18n.t("workspace.alerting.screenCopy.detailsHidden"),
		dailyReports: i18n.t("workspace.alerting.screenCopy.dailyReports"),
		dailyReportsDescription: i18n.t("workspace.alerting.screenCopy.dailyReportsDescription"),
		settings: i18n.t("workspace.alerting.screenCopy.settings"),
		preview: i18n.t("workspace.alerting.screenCopy.preview"),
		reportHistory: i18n.t("workspace.alerting.screenCopy.reportHistory"),
		timezone: i18n.t("workspace.alerting.screenCopy.timezone"),
		generateTime: i18n.t("workspace.alerting.screenCopy.generateTime"),
		sendTime: i18n.t("workspace.alerting.screenCopy.sendTime"),
		slowThreshold: i18n.t("workspace.alerting.screenCopy.slowThreshold"),
		internalAudience: i18n.t("workspace.alerting.screenCopy.internalAudience"),
		externalAudience: i18n.t("workspace.alerting.screenCopy.externalAudience"),
		saveSettings: i18n.t("workspace.alerting.screenCopy.saveSettings"),
		previewReport: i18n.t("workspace.alerting.screenCopy.previewReport"),
		generateReport: i18n.t("workspace.alerting.screenCopy.generateReport"),
		generateAndSend: i18n.t("workspace.alerting.screenCopy.generateAndSend"),
		businessDate: i18n.t("workspace.alerting.screenCopy.businessDate"),
		progress: i18n.t("workspace.alerting.screenCopy.progress"),
		resendInternal: i18n.t("workspace.alerting.screenCopy.resendInternal"),
		resendExternal: i18n.t("workspace.alerting.screenCopy.resendExternal"),
		audience: i18n.t("workspace.alerting.screenCopy.audience"),
		internal: i18n.t("workspace.alerting.screenCopy.internal"),
		external: i18n.t("workspace.alerting.screenCopy.external"),
		allAudiences: i18n.t("workspace.alerting.screenCopy.allAudiences"),
		generatedAt: i18n.t("workspace.alerting.screenCopy.generatedAt"),
		viewDetails: i18n.t("workspace.alerting.screenCopy.viewDetails"),
		reportSaved: i18n.t("workspace.alerting.screenCopy.reportSaved"),
		jobStarted: i18n.t("workspace.alerting.screenCopy.jobStarted"),
		deliveryAttempted: i18n.t("workspace.alerting.screenCopy.deliveryAttempted"),
		externalPrivacy: i18n.t("workspace.alerting.screenCopy.externalPrivacy"),
		noReports: i18n.t("workspace.alerting.screenCopy.noReports"),
		dailyStatus: {
			running: i18n.t("workspace.alerting.screenCopy.dailyStatus_running"),
			prepared: i18n.t("workspace.alerting.screenCopy.dailyStatus_prepared"),
			success: i18n.t("workspace.alerting.screenCopy.dailyStatus_success"),
			partial: i18n.t("workspace.alerting.screenCopy.dailyStatus_partial"),
			failed: i18n.t("workspace.alerting.screenCopy.dailyStatus_failed"),
			pending: i18n.t("workspace.alerting.screenCopy.dailyStatus_pending"),
			delivered: i18n.t("workspace.alerting.screenCopy.dailyStatus_delivered"),
			not_enabled: i18n.t("workspace.alerting.screenCopy.dailyStatus_not_enabled"),
			no_channels: i18n.t("workspace.alerting.screenCopy.dailyStatus_no_channels"),
		},
	};
}