const content = {
	en: {
		rules: "Alert rules",
		rulesDescription: "Evaluate provider and model reliability over a rolling window and notify configured channels.",
		channels: "Alert channels",
		channelsDescription: "Secrets are write-only and are never displayed after saving.",
		history: "Alert history",
		historyDescription: "Review safe delivery outcomes and evaluation context.",
		privateWarning: "Private or HTTP destinations are blocked unless webhook_network is explicitly enabled in server config.",
		add: "Add",
		save: "Save",
		cancel: "Cancel",
		delete: "Delete",
		edit: "Edit",
		test: "Test",
		evaluate: "Evaluate now",
		noItems: "Nothing configured yet.",
		beta: "Beta",
		name: "Name",
		type: "Type",
		status: "Status",
		enabled: "Enabled",
		disabled: "Disabled",
		description: "Description",
		webhookUrl: "Webhook URL",
		routingKey: "Routing key",
		headersJson: "Headers JSON",
		keepSecret: "Leave empty to keep the saved secret",
		channelSaved: "Alert channel saved",
		testSent: "Test notification sent",
		scope: "Scope",
		scopeId: "Scope ID",
		provider: "Provider",
		modelTarget: "Model target (optional)",
		budgetTarget: "Budget target (optional)",
		window: "Window",
		minimumRequests: "Minimum requests",
		cooldown: "Cooldown",
		notifyOnce: "Notify once per reset cycle",
		cel: "CEL condition",
		celHelp:
			"Provider metrics include provider_error_rate, provider_error_count, provider_success_count and provider_request_count. Conditions run after the window reaches the minimum request count.",
		evaluateDescription: "Run this rule now. You may override its cooldown for incident testing.",
		ignoreCooldown: "Ignore cooldown",
		evaluateButton: "Evaluate",
		ruleSaved: "Alert rule saved",
		evaluationCompleted: "Evaluation completed",
		evaluationResult: (matched: number, sent: number) => `Matched ${matched}; sent ${sent}`,
		time: "Time",
		rule: "Rule",
		channel: "Channel",
		deliveryDetails: "Delivery status details",
		genericWebhook: "Generic webhook",
		allScopes: "All scopes",
		allChannels: "All channels",
		scopeLabels: { provider: "Provider", virtual_key: "Virtual key", team: "Team", customer: "Customer" },
		statusLabels: { all: "All statuses", sent: "Sent", failed: "Failed", skipped: "Skipped" },
		units: { minutes: "minutes", hours: "hours", days: "days" },
		detailsHidden: "Delivery details are hidden; inspect server logs for diagnostics.",
	},
	zh: {
		rules: "告警规则",
		rulesDescription: "在滚动时间窗口内评估供应商和模型可靠性，并通知已配置渠道。",
		channels: "告警渠道",
		channelsDescription: "密钥仅可写入，保存后不会再次显示。",
		history: "告警历史",
		historyDescription: "查看安全的发送结果和评估上下文。",
		privateWarning: "除非在服务端 webhook_network 配置中明确允许，否则会阻止私网或 HTTP 地址。",
		add: "添加",
		save: "保存",
		cancel: "取消",
		delete: "删除",
		edit: "编辑",
		test: "测试",
		evaluate: "立即评估",
		noItems: "暂无配置。",
		beta: "测试版",
		name: "名称",
		type: "类型",
		status: "状态",
		enabled: "已启用",
		disabled: "已停用",
		description: "描述",
		webhookUrl: "Webhook 地址",
		routingKey: "路由密钥",
		headersJson: "请求头 JSON",
		keepSecret: "留空以保留已保存的密钥",
		channelSaved: "告警渠道已保存",
		testSent: "测试通知已发送",
		scope: "范围",
		scopeId: "范围 ID",
		provider: "供应商",
		modelTarget: "模型目标（可选）",
		budgetTarget: "预算目标（可选）",
		window: "时间窗口",
		minimumRequests: "最小请求数",
		cooldown: "冷却时间",
		notifyOnce: "每个重置周期仅通知一次",
		cel: "CEL 条件",
		celHelp:
			"供应商指标包括 provider_error_rate、provider_error_count、provider_success_count 和 provider_request_count。达到最小请求数后才会评估条件。",
		evaluateDescription: "立即运行此规则；事故演练时可忽略冷却时间。",
		ignoreCooldown: "忽略冷却时间",
		evaluateButton: "执行评估",
		ruleSaved: "告警规则已保存",
		evaluationCompleted: "评估已完成",
		evaluationResult: (matched: number, sent: number) => `匹配 ${matched} 个目标，发送 ${sent} 条通知`,
		time: "时间",
		rule: "规则",
		channel: "渠道",
		deliveryDetails: "发送状态详情",
		genericWebhook: "通用 Webhook",
		allScopes: "全部范围",
		allChannels: "全部渠道",
		scopeLabels: { provider: "供应商", virtual_key: "虚拟密钥", team: "团队", customer: "客户" },
		statusLabels: { all: "全部状态", sent: "已发送", failed: "失败", skipped: "已跳过" },
		units: { minutes: "分钟", hours: "小时", days: "天" },
		detailsHidden: "发送详情已隐藏，请在服务端日志中查看诊断信息。",
	},
} as const;
export function alertingCopy() {
	return typeof document !== "undefined" && document.documentElement.lang.toLowerCase().startsWith("zh") ? content.zh : content.en;
}