import i18n from "@/lib/i18n";

const labelKeys: Record<string, string> = {
	Observability: "sidebar.nav.observability",
	Models: "sidebar.nav.models",
	"MCP Gateway": "sidebar.nav.mcpGateway",
	Plugins: "sidebar.nav.plugins",
	Alerting: "sidebar.nav.alerting",
	Governance: "sidebar.nav.governance",
	Guardrails: "sidebar.nav.guardrails",
	Webhooks: "sidebar.nav.webhooks",
	"Cluster Config": "sidebar.nav.clusterConfig",
	"Adaptive Routing": "sidebar.nav.adaptiveRouting",
	"Prompt Repository": "sidebar.nav.promptRepository",
	"Skills Repository": "sidebar.nav.skillsRepository",
	Settings: "sidebar.nav.settings",
	Dashboard: "sidebar.sub.dashboard",
	"LLM Logs": "sidebar.sub.llmLogs",
	"MCP Logs": "sidebar.sub.mcpLogs",
	Connectors: "sidebar.sub.connectors",
	"Logs Settings": "sidebar.sub.logsSettings",
	"Model Catalog": "sidebar.sub.modelCatalog",
	"Model Providers": "sidebar.sub.modelProviders",
	"Budgets & Limits": "sidebar.sub.budgetsLimits",
	"Routing Rules": "sidebar.sub.routingRules",
	"Complexity Router": "sidebar.sub.complexityRouter",
	"Circuit Breaker": "sidebar.sub.circuitBreaker",
	"Pricing Overrides": "sidebar.sub.pricingOverrides",
	"Model Settings": "sidebar.sub.modelSettings",
	"MCP Catalog": "sidebar.sub.mcpCatalog",
	"MCP Library": "sidebar.sub.mcpLibrary",
	"Tool Groups": "sidebar.sub.toolGroups",
	"Auth Sessions": "sidebar.sub.authSessions",
	"OAuth Grants": "sidebar.sub.oauthGrants",
	"MCP Settings": "sidebar.sub.mcpSettings",
	Channels: "sidebar.sub.channels",
	Rules: "sidebar.sub.rules",
	History: "sidebar.sub.history",
	"Daily Reports": "sidebar.sub.dailyReports",
	"Virtual Keys": "sidebar.sub.virtualKeys",
	Users: "sidebar.sub.users",
	Teams: "sidebar.sub.teams",
	"Business Units": "sidebar.sub.businessUnits",
	Customers: "sidebar.sub.customers",
	"User Provisioning": "sidebar.sub.userProvisioning",
	"Roles & Permissions": "sidebar.sub.rolesPermissions",
	"Access Profiles": "sidebar.sub.accessProfiles",
	"Audit Logs": "sidebar.sub.auditLogs",
	Providers: "sidebar.sub.providers",
	"Client Settings": "sidebar.sub.clientSettings",
	Compatibility: "sidebar.sub.compatibility",
	Caching: "sidebar.sub.caching",
	Security: "sidebar.sub.security",
	Proxy: "sidebar.sub.proxy",
	"API Keys": "sidebar.sub.apiKeys",
	"Performance Tuning": "sidebar.sub.performanceTuning",
	"Feature Flags": "sidebar.sub.featureFlags",
};

export function sidebarLabel(label: string) {
	return labelKeys[label] ? i18n.t(labelKeys[label], { defaultValue: label }) : label;
}

export const sidebarCopy = () => ({
	collapse: i18n.t("systemCopy.sidebarCopy_collapse_sidebar"),
	expand: i18n.t("systemCopy.sidebarCopy_expand_sidebar"),
	searchNavigation: i18n.t("systemCopy.sidebarCopy_search_sidebar_navigation"),
	searchPlaceholder: i18n.t("systemCopy.sidebarCopy_search"),
});