import { localize } from "@/lib/i18n/language";

const chineseLabels: Record<string, string> = {
	Observability: "可观测性",
	Models: "模型",
	"MCP Gateway": "MCP 网关",
	Plugins: "插件",
	Alerting: "告警",
	Governance: "治理",
	Guardrails: "防护规则",
	Webhooks: "Webhook",
	"Cluster Config": "集群配置",
	"Adaptive Routing": "自适应路由",
	"Prompt Repository": "提示词仓库",
	"Skills Repository": "技能仓库",
	Settings: "设置",
	Dashboard: "仪表盘",
	"LLM Logs": "LLM 日志",
	"MCP Logs": "MCP 日志",
	Connectors: "连接器",
	"Logs Settings": "日志设置",
	"Model Catalog": "模型目录",
	"Model Providers": "模型供应商",
	"Budgets & Limits": "预算与限制",
	"Routing Rules": "路由规则",
	"Complexity Router": "复杂度路由",
	"Circuit Breaker": "熔断器",
	"Pricing Overrides": "定价覆盖",
	"Model Settings": "模型设置",
	"MCP Catalog": "MCP 目录",
	"MCP Library": "MCP 资源库",
	"Tool Groups": "工具组",
	"Auth Sessions": "认证会话",
	"OAuth Grants": "OAuth 授权",
	"MCP Settings": "MCP 设置",
	Channels: "渠道",
	Rules: "规则",
	History: "历史",
	"Daily Reports": "每日报告",
	"Virtual Keys": "虚拟密钥",
	Users: "用户",
	Teams: "团队",
	"Business Units": "业务单元",
	Customers: "客户",
	"User Provisioning": "用户配置",
	"Roles & Permissions": "角色与权限",
	"Access Profiles": "访问配置",
	"Audit Logs": "审计日志",
	Providers: "供应商",
	"Client Settings": "客户端设置",
	Compatibility: "兼容性",
	Caching: "缓存",
	Security: "安全",
	Proxy: "代理",
	"API Keys": "API 密钥",
	"Performance Tuning": "性能调优",
	"Feature Flags": "功能开关",
};

export function sidebarLabel(label: string) {
	return localize(label, chineseLabels[label] ?? label);
}

export const sidebarCopy = () => ({
	collapse: localize("Collapse sidebar", "收起侧边栏"),
	expand: localize("Expand sidebar", "展开侧边栏"),
	searchNavigation: localize("Search sidebar navigation", "搜索侧边栏导航"),
	searchPlaceholder: localize("Search...", "搜索..."),
});