import { localize } from "@/lib/i18n/language";

export const routingRulesCopy = {
	off: localize("Off", "已关闭"),
	priority: localize("Priority", "优先级"),
	target: localize("target", "目标"),
	targets: localize("Targets", "目标"),
	chainRule: localize("Chain rule", "链式规则"),
	chainRuleHelp: localize(
		"Resolved provider/model feeds back as the new input and the full scope chain re-evaluates.",
		"解析后的供应商和模型将作为新输入，并重新评估完整的作用域规则链。",
	),
	resolvedTarget: localize("Resolved target (new input)", "解析目标（新输入）"),
	passthrough: localize("Passthrough", "保持原值"),
	originalProviderModel: localize("original provider & model", "原始供应商和模型"),
	incomingRequest: localize("Incoming Request", "传入请求"),
	incomingRequestFields: localize("provider · model · headers · params · limits", "供应商 · 模型 · 请求头 · 参数 · 限制"),
	treeNeedsLargerScreen: localize("Routing tree needs a larger screen", "路由树需要更大的屏幕"),
	treeMobileHelp: localize("Use the routing rules list to review and modify rules on mobile.", "请在移动端使用路由规则列表查看和修改规则。"),
	viewRoutingRules: localize("View routing rules", "查看路由规则"),
	failedToLoad: localize("Failed to load routing rules", "加载路由规则失败"),
	noRulesToDisplay: localize("No routing rules to display", "暂无可显示的路由规则"),
	backToRules: localize("Back to rules", "返回规则列表"),
	back: localize("Back", "返回"),
	routingTree: localize("Routing Tree", "路由树"),
	noMatch: localize("no match", "未匹配"),
	searchConditions: localize("Search conditions or rules…", "搜索条件或规则…"),
	resetLayoutTitle: localize("Reset to default layout", "恢复默认布局"),
	resetLayout: localize("Reset layout", "重置布局"),
	staticChain: localize("Static chain", "静态链路"),
	staticChainHelp: localize(
		"Re-entry point is fully proven by static analysis; every condition on the path evaluated to a known value.",
		"静态分析已完全确认重新进入点；路径上的每个条件都已求值得到确定结果。",
	),
	dynamicChain: localize("Dynamic chain", "动态链路"),
	dynamicChainHelp: localize(
		"Re-entry point is a conditional; one or more conditions on the path are not fully evaluated at build time.",
		"重新进入点带有条件；路径上的一个或多个条件无法在构建时完全求值。",
	),
	copyFailed: localize("Failed to copy to clipboard", "复制到剪贴板失败"),
	copied: localize("Copied!", "已复制"),
	value: localize("value", "值"),
	copiedLabel: (label: string) => localize(`${label} copied`, `${label}已复制`),
	copyLabel: (label: string) => localize(`Copy ${label}`, `复制${label}`),
	header: localize("header", "请求头"),
	param: localize("param", "参数"),
	group: localize("Group", "条件组"),
	incomingModel: localize("Incoming model", "传入模型"),
	incomingProvider: localize("Incoming provider", "传入供应商"),
	weight: localize("Weight", "权重"),
	raw: localize("raw", "原始值"),
	pinnedKey: localize("Pinned key", "固定密钥"),
	keyId: localize("key ID", "密钥 ID"),
	expressionLabel: localize("expression", "表达式"),
	ruleEntity: localize("rule", "规则"),
	enabled: localize("Enabled", "已启用"),
	disabled: localize("Disabled", "已停用"),
	chainRuleDetail: localize(
		"After this rule matches, routing rules are re-evaluated using the resolved provider/model as the new context.",
		"此规则匹配后，将以解析后的供应商和模型作为新上下文重新评估路由规则。",
	),
	overview: localize("Overview", "概览"),
	scope: localize("Scope", "作用域"),
	conditions: localize("Conditions", "条件"),
	definedAsCel: localize("Defined as a CEL expression below", "由下方 CEL 表达式定义"),
	matchesAll: localize("Matches all requests", "匹配所有请求"),
	celExpression: localize("CEL Expression", "CEL 表达式"),
	noTargets: localize("No targets configured", "未配置目标"),
	fallbackChain: localize("Fallback Chain", "Fallback 链"),
	noFallbacks: localize("No fallbacks configured", "未配置 Fallback"),
	created: localize("Created", "创建时间"),
	lastUpdated: localize("Last Updated", "最后更新时间"),
	loadingCelBuilder: localize("Loading CEL builder...", "正在加载 CEL 规则编辑器…"),
	atLeastOneTarget: localize("At least one routing target is required", "至少需要一个路由目标"),
	positiveTargetWeight: localize("Each target weight must be greater than 0", "每个目标的权重必须大于 0"),
	scopeRequired: (scope: string) => localize(`${scope} is required`, `请选择${scope}`),
	weightsMustSum: (total: string) => localize(`Target weights must sum to 1, current total: ${total}`, `目标权重总和必须为 1，当前为 ${total}`),
	invalidRegex: (details: string) => localize(`Invalid regex pattern:\n${details}`, `正则表达式无效：\n${details}`),
	invalidRuleConfig: (details: string) => localize(`Invalid rule configuration:\n${details}`, `规则配置无效：\n${details}`),
	updateSuccess: localize("Routing rule updated successfully", "路由规则已更新"),
	createSuccess: localize("Routing rule created successfully", "路由规则已创建"),
	editRule: localize("Edit Routing Rule", "编辑路由规则"),
	createRule: localize("Create New Routing Rule", "新建路由规则"),
	updateRuleDescription: localize("Update the routing rule configuration", "更新路由规则配置"),
	createRuleDescription: localize("Create a new CEL-based routing rule for intelligent request routing", "创建基于 CEL 的智能请求路由规则"),
	ruleName: localize("Rule Name", "规则名称"),
	ruleNamePlaceholder: localize("e.g., Route GPT-4 to Azure", "例如：将 GPT-4 路由到 Azure"),
	ruleNameRequired: localize("Rule name is required", "请输入规则名称"),
	description: localize("Description", "描述"),
	descriptionPlaceholder: localize("Describe what this rule does...", "描述这条规则的用途…"),
	enableRule: localize("Enable Rule", "启用规则"),
	enableRuleHelp: localize("Rule will be active and applied to matching requests", "规则将启用并应用于匹配的请求"),
	chainRuleEditorHelp: localize(
		"After this rule matches, re-evaluate routing rules using the resolved provider/model as the new context. Useful for composing rules, e.g. normalize a model alias first, then route based on the canonical name.",
		"此规则匹配后，以解析后的供应商和模型作为新上下文重新评估规则。可用于组合规则，例如先规范化模型别名，再按标准名称路由。",
	),
	selectScope: localize("Select scope...", "选择作用域…"),
	user: localize("User", "用户"),
	team: localize("Team", "团队"),
	customer: localize("Customer", "客户"),
	virtualKey: localize("Virtual Key", "虚拟密钥"),
	priorityHelp: localize("Lower numbers = higher priority (0 is highest)", "数字越小优先级越高（0 为最高）"),
	priorityRequired: localize("Priority is required", "请输入优先级"),
	priorityMin: localize("Priority must be ≥ 0", "优先级必须大于或等于 0"),
	priorityMax: localize("Priority must be ≤ 1000", "优先级必须小于或等于 1000"),
	governanceUserId: localize("Governance user ID", "治理用户 ID"),
	ruleBuilder: localize("Rule Builder", "规则编辑器"),
	ruleBuilderHelp: localize(
		"Build conditions to determine when this rule should apply. Leave empty to apply this rule to all requests.",
		"构建规则生效条件。留空表示应用于所有请求。",
	),
	governancePrerequisite: localize(
		"Ensure token limits, request limits, and budgets are configured under Model Providers before using them in routing rules.",
		"在路由规则中使用 Token、请求次数或预算条件前，请先在模型供应商中完成相应限制配置。",
	),
	routingTargets: localize("Routing Targets", "路由目标"),
	routingTargetsHelp: localize(
		"Weights must sum to 1. Leave provider or model empty to use the incoming request value.",
		"权重总和必须为 1。供应商或模型留空时沿用传入请求的值。",
	),
	addTarget: localize("Add Target", "添加目标"),
	totalWeight: localize("Total weight", "总权重"),
	mustEqualOne: localize("must equal 1", "必须等于 1"),
	fallbacks: localize("Fallbacks", "Fallback"),
	fallbacksHelp: localize(
		"Provider is required, but model is optional. Leave model empty to use the incoming request value.",
		"供应商必填，模型可选；模型留空时沿用传入请求的值。",
	),
	addFallback: localize("Add Fallback", "添加 Fallback"),
	selectProvider: localize("Select provider...", "选择供应商…"),
	incomingOptional: localize("Incoming (optional)", "沿用传入值（可选）"),
	fallbackOrderHelp: localize("Fallbacks will be used in the order they are defined", "Fallback 将按定义顺序依次使用"),
	cancel: localize("Cancel", "取消"),
	updateRule: localize("Update Rule", "更新规则"),
	saveRule: localize("Save Rule", "保存规则"),
	provider: localize("Provider", "供应商"),
	model: localize("Model", "模型"),
	apiKey: localize("API Key", "API 密钥"),
	apiKeyOptional: localize("optional; leave unset for load-balanced selection", "可选；留空时使用负载均衡选择"),
	selectKey: localize("Select key (optional)", "选择密钥（可选）"),
	pinned: localize("pinned", "已固定"),
	removeFallback: (index: number) => localize(`Remove fallback ${index}`, `删除第 ${index} 个 Fallback`),
	removeTarget: (index: number) => localize(`Remove target ${index}`, `删除第 ${index} 个目标`),
	clearProvider: (index: number) => localize(`Clear provider for target ${index}`, `清除第 ${index} 个目标的供应商`),
	clearModel: (index: number) => localize(`Clear model for target ${index}`, `清除第 ${index} 个目标的模型`),
	clearApiKey: (index: number) => localize(`Clear API key for target ${index}`, `清除第 ${index} 个目标的 API 密钥`),
	emptyTitle: localize("Routing rules direct requests using CEL conditions", "路由规则通过 CEL 条件分发请求"),
	emptyDescription: localize(
		"Create CEL-based rules to route requests by model, provider, budget, or custom attributes. Control which provider or model handles each request.",
		"创建基于 CEL 的规则，按模型、供应商、预算或自定义属性分发请求，并控制每个请求由哪个供应商或模型处理。",
	),
	readMoreAria: localize("Read more about routing rules (opens in new tab)", "了解更多路由规则信息（在新标签页打开）"),
	readMore: localize("Read more", "了解更多"),
	createFirstRule: localize("Create your first routing rule", "创建第一条路由规则"),
	newRule: localize("New Rule", "新建规则"),
	edit: localize("Edit", "编辑"),
	delete: localize("Delete", "删除"),
	deleteSuccess: localize("Routing rule deleted successfully", "路由规则已删除"),
	name: localize("Name", "名称"),
	expression: localize("Expression", "表达式"),
	actions: localize("Actions", "操作"),
	status: localize("Status", "状态"),
	searchRulesTitle: localize("Search routing rules by name", "按名称搜索路由规则"),
	searchRulesPlaceholder: localize("Search by name...", "按名称搜索…"),
	noMatchingRules: localize("No matching routing rules found.", "未找到匹配的路由规则。"),
	updateFailed: localize("Failed to update rule", "更新规则失败"),
	actionsForRule: (name: string) => localize(`Actions for routing rule ${name}`, `路由规则 ${name} 的操作`),
	ruleStatusChanged: (enabled: boolean) => localize(`Rule ${enabled ? "enabled" : "disabled"} successfully`, `规则已${enabled ? "启用" : "停用"}`),
	previousPage: localize("Previous page", "上一页"),
	nextPage: localize("Next page", "下一页"),
	page: localize("Page", "第"),
	of: localize("of", "共"),
	entries: localize("entries", "条"),
	deleteRule: localize("Delete Routing Rule", "删除路由规则"),
	deleteRuleConfirm: (name: string) => localize(`Are you sure you want to delete "${name}"? This action cannot be undone.`, `确定要删除“${name}”吗？此操作无法撤销。`),
	deleting: localize("Deleting...", "正在删除…"),
	moreTargets: (count: number) => localize(`+${count} more target${count === 1 ? "" : "s"}`, `另有 ${count} 个目标`),
	any: localize("Any", "任意"),
	anyModel: localize("Any model", "任意模型"),
	pageSummary: (start: number, end: number, total: number) => localize(`${start}-${end} of ${total} entries`, `第 ${start}-${end} 条，共 ${total} 条`),
	manageDescription: localize("Manage CEL-based routing rules for intelligent request routing across providers", "管理基于 CEL 的规则，在不同供应商之间智能分发请求"),
	viewTreeTitle: localize("View routing rules tree", "查看路由规则树"),
	viewTree: localize("View Tree", "查看路由树"),
	newRuleTitle: localize("New routing rule", "新建路由规则"),
	ruleCount: (count: number) => localize(`${count} rule${count === 1 ? "" : "s"}`, `${count} 条规则`),
	targetCount: (count: number) => localize(`${count} target${count === 1 ? "" : "s"}`, `${count} 个目标`),
	scopeLabel: (scope: string) =>
		({
			global: localize("Global", "全局"),
			team: localize("Team", "团队"),
			customer: localize("Customer", "客户"),
			virtual_key: localize("Virtual Key", "虚拟密钥"),
			user: localize("User", "用户"),
		})[scope] ?? scope,
};
