import i18n from "@/lib/i18n";

export const routingRulesCopy = {
	off: i18n.t("workspace.routingRules.copy.off"),
	priority: i18n.t("workspace.routingRules.copy.priority"),
	target: i18n.t("workspace.routingRules.copy.target"),
	targets: i18n.t("workspace.routingRules.copy.targets"),
	chainRule: i18n.t("workspace.routingRules.copy.chainRule"),
	chainRuleHelp: i18n.t("workspace.routingRules.copy.chainRuleHelp"),
	resolvedTarget: i18n.t("workspace.routingRules.copy.resolvedTarget"),
	passthrough: i18n.t("workspace.routingRules.copy.passthrough"),
	originalProviderModel: i18n.t("workspace.routingRules.copy.originalProviderModel"),
	incomingRequest: i18n.t("workspace.routingRules.copy.incomingRequest"),
	incomingRequestFields: i18n.t("workspace.routingRules.copy.incomingRequestFields"),
	treeNeedsLargerScreen: i18n.t("workspace.routingRules.copy.treeNeedsLargerScreen"),
	treeMobileHelp: i18n.t("workspace.routingRules.copy.treeMobileHelp"),
	viewRoutingRules: i18n.t("workspace.routingRules.copy.viewRoutingRules"),
	failedToLoad: i18n.t("workspace.routingRules.copy.failedToLoad"),
	noRulesToDisplay: i18n.t("workspace.routingRules.copy.noRulesToDisplay"),
	backToRules: i18n.t("workspace.routingRules.copy.backToRules"),
	back: i18n.t("workspace.routingRules.copy.back"),
	routingTree: i18n.t("workspace.routingRules.copy.routingTree"),
	noMatch: i18n.t("workspace.routingRules.copy.noMatch"),
	searchConditions: i18n.t("workspace.routingRules.copy.searchConditions"),
	resetLayoutTitle: i18n.t("workspace.routingRules.copy.resetLayoutTitle"),
	resetLayout: i18n.t("workspace.routingRules.copy.resetLayout"),
	staticChain: i18n.t("workspace.routingRules.copy.staticChain"),
	staticChainHelp: i18n.t("workspace.routingRules.copy.staticChainHelp"),
	dynamicChain: i18n.t("workspace.routingRules.copy.dynamicChain"),
	dynamicChainHelp: i18n.t("workspace.routingRules.copy.dynamicChainHelp"),
	copyFailed: i18n.t("workspace.routingRules.copy.copyFailed"),
	copied: i18n.t("workspace.routingRules.copy.copied"),
	value: i18n.t("workspace.routingRules.copy.value"),
	copiedLabel: (label: string) => i18n.t("workspace.routingRules.copy.copiedLabel", { value0: label }),
	copyLabel: (label: string) => i18n.t("workspace.routingRules.copy.copyLabel", { value0: label }),
	header: i18n.t("workspace.routingRules.copy.header"),
	param: i18n.t("workspace.routingRules.copy.param"),
	group: i18n.t("workspace.routingRules.copy.group"),
	incomingModel: i18n.t("workspace.routingRules.copy.incomingModel"),
	incomingProvider: i18n.t("workspace.routingRules.copy.incomingProvider"),
	weight: i18n.t("workspace.routingRules.copy.weight"),
	raw: i18n.t("workspace.routingRules.copy.raw"),
	pinnedKey: i18n.t("workspace.routingRules.copy.pinnedKey"),
	keyId: i18n.t("workspace.routingRules.copy.keyId"),
	expressionLabel: i18n.t("workspace.routingRules.copy.expressionLabel"),
	ruleEntity: i18n.t("workspace.routingRules.copy.ruleEntity"),
	enabled: i18n.t("workspace.routingRules.copy.enabled"),
	disabled: i18n.t("workspace.routingRules.copy.disabled"),
	chainRuleDetail: i18n.t("workspace.routingRules.copy.chainRuleDetail"),
	overview: i18n.t("workspace.routingRules.copy.overview"),
	scope: i18n.t("workspace.routingRules.copy.scope"),
	conditions: i18n.t("workspace.routingRules.copy.conditions"),
	definedAsCel: i18n.t("workspace.routingRules.copy.definedAsCel"),
	matchesAll: i18n.t("workspace.routingRules.copy.matchesAll"),
	celExpression: i18n.t("workspace.routingRules.copy.celExpression"),
	noTargets: i18n.t("workspace.routingRules.copy.noTargets"),
	fallbackChain: i18n.t("workspace.routingRules.copy.fallbackChain"),
	noFallbacks: i18n.t("workspace.routingRules.copy.noFallbacks"),
	created: i18n.t("workspace.routingRules.copy.created"),
	lastUpdated: i18n.t("workspace.routingRules.copy.lastUpdated"),
	loadingCelBuilder: i18n.t("workspace.routingRules.copy.loadingCelBuilder"),
	atLeastOneTarget: i18n.t("workspace.routingRules.copy.atLeastOneTarget"),
	positiveTargetWeight: i18n.t("workspace.routingRules.copy.positiveTargetWeight"),
	scopeRequired: (scope: string) => i18n.t("workspace.routingRules.copy.scopeRequired", { value0: scope }),
	weightsMustSum: (total: string) => i18n.t("workspace.routingRules.copy.weightsMustSum", { value0: total }),
	invalidRegex: (details: string) => i18n.t("workspace.routingRules.copy.invalidRegex", { value0: details }),
	invalidRuleConfig: (details: string) => i18n.t("workspace.routingRules.copy.invalidRuleConfig", { value0: details }),
	updateSuccess: i18n.t("workspace.routingRules.copy.updateSuccess"),
	createSuccess: i18n.t("workspace.routingRules.copy.createSuccess"),
	editRule: i18n.t("workspace.routingRules.copy.editRule"),
	createRule: i18n.t("workspace.routingRules.copy.createRule"),
	updateRuleDescription: i18n.t("workspace.routingRules.copy.updateRuleDescription"),
	createRuleDescription: i18n.t("workspace.routingRules.copy.createRuleDescription"),
	ruleName: i18n.t("workspace.routingRules.copy.ruleName"),
	ruleNamePlaceholder: i18n.t("workspace.routingRules.copy.ruleNamePlaceholder"),
	ruleNameRequired: i18n.t("workspace.routingRules.copy.ruleNameRequired"),
	description: i18n.t("workspace.routingRules.copy.description"),
	descriptionPlaceholder: i18n.t("workspace.routingRules.copy.descriptionPlaceholder"),
	enableRule: i18n.t("workspace.routingRules.copy.enableRule"),
	enableRuleHelp: i18n.t("workspace.routingRules.copy.enableRuleHelp"),
	chainRuleEditorHelp: i18n.t("workspace.routingRules.copy.chainRuleEditorHelp"),
	selectScope: i18n.t("workspace.routingRules.copy.selectScope"),
	user: i18n.t("workspace.routingRules.copy.user"),
	team: i18n.t("workspace.routingRules.copy.team"),
	customer: i18n.t("workspace.routingRules.copy.customer"),
	virtualKey: i18n.t("workspace.routingRules.copy.virtualKey"),
	priorityHelp: i18n.t("workspace.routingRules.copy.priorityHelp"),
	priorityRequired: i18n.t("workspace.routingRules.copy.priorityRequired"),
	priorityMin: i18n.t("workspace.routingRules.copy.priorityMin"),
	priorityMax: i18n.t("workspace.routingRules.copy.priorityMax"),
	governanceUserId: i18n.t("workspace.routingRules.copy.governanceUserId"),
	ruleBuilder: i18n.t("workspace.routingRules.copy.ruleBuilder"),
	ruleBuilderHelp: i18n.t("workspace.routingRules.copy.ruleBuilderHelp"),
	governancePrerequisite: i18n.t("workspace.routingRules.copy.governancePrerequisite"),
	routingTargets: i18n.t("workspace.routingRules.copy.routingTargets"),
	routingTargetsHelp: i18n.t("workspace.routingRules.copy.routingTargetsHelp"),
	addTarget: i18n.t("workspace.routingRules.copy.addTarget"),
	totalWeight: i18n.t("workspace.routingRules.copy.totalWeight"),
	mustEqualOne: i18n.t("workspace.routingRules.copy.mustEqualOne"),
	fallbacks: i18n.t("workspace.routingRules.copy.fallbacks"),
	fallbacksHelp: i18n.t("workspace.routingRules.copy.fallbacksHelp"),
	addFallback: i18n.t("workspace.routingRules.copy.addFallback"),
	selectProvider: i18n.t("workspace.routingRules.copy.selectProvider"),
	incomingOptional: i18n.t("workspace.routingRules.copy.incomingOptional"),
	fallbackOrderHelp: i18n.t("workspace.routingRules.copy.fallbackOrderHelp"),
	cancel: i18n.t("workspace.routingRules.copy.cancel"),
	updateRule: i18n.t("workspace.routingRules.copy.updateRule"),
	saveRule: i18n.t("workspace.routingRules.copy.saveRule"),
	provider: i18n.t("workspace.routingRules.copy.provider"),
	model: i18n.t("workspace.routingRules.copy.model"),
	apiKey: i18n.t("workspace.routingRules.copy.apiKey"),
	apiKeyOptional: i18n.t("workspace.routingRules.copy.apiKeyOptional"),
	selectKey: i18n.t("workspace.routingRules.copy.selectKey"),
	pinned: i18n.t("workspace.routingRules.copy.pinned"),
	removeFallback: (index: number) => i18n.t("workspace.routingRules.copy.removeFallback", { value0: index }),
	removeTarget: (index: number) => i18n.t("workspace.routingRules.copy.removeTarget", { value0: index }),
	clearProvider: (index: number) => i18n.t("workspace.routingRules.copy.clearProvider", { value0: index }),
	clearModel: (index: number) => i18n.t("workspace.routingRules.copy.clearModel", { value0: index }),
	clearApiKey: (index: number) => i18n.t("workspace.routingRules.copy.clearApiKey", { value0: index }),
	emptyTitle: i18n.t("workspace.routingRules.copy.emptyTitle"),
	emptyDescription: i18n.t("workspace.routingRules.copy.emptyDescription"),
	readMoreAria: i18n.t("workspace.routingRules.copy.readMoreAria"),
	readMore: i18n.t("workspace.routingRules.copy.readMore"),
	createFirstRule: i18n.t("workspace.routingRules.copy.createFirstRule"),
	newRule: i18n.t("workspace.routingRules.copy.newRule"),
	edit: i18n.t("workspace.routingRules.copy.edit"),
	delete: i18n.t("workspace.routingRules.copy.delete"),
	deleteSuccess: i18n.t("workspace.routingRules.copy.deleteSuccess"),
	name: i18n.t("workspace.routingRules.copy.name"),
	expression: i18n.t("workspace.routingRules.copy.expression"),
	actions: i18n.t("workspace.routingRules.copy.actions"),
	status: i18n.t("workspace.routingRules.copy.status"),
	searchRulesTitle: i18n.t("workspace.routingRules.copy.searchRulesTitle"),
	searchRulesPlaceholder: i18n.t("workspace.routingRules.copy.searchRulesPlaceholder"),
	noMatchingRules: i18n.t("workspace.routingRules.copy.noMatchingRules"),
	updateFailed: i18n.t("workspace.routingRules.copy.updateFailed"),
	actionsForRule: (name: string) => i18n.t("workspace.routingRules.copy.actionsForRule", { value0: name }),
	ruleStatusChanged: (enabled: boolean) =>
		i18n.t("workspace.routingRules.copy.ruleStatusChanged", {
			state: i18n.t(enabled ? "workspace.routingRules.copy.stateEnabled" : "workspace.routingRules.copy.stateDisabled"),
		}),
	previousPage: i18n.t("workspace.routingRules.copy.previousPage"),
	nextPage: i18n.t("workspace.routingRules.copy.nextPage"),
	page: i18n.t("workspace.routingRules.copy.page"),
	of: i18n.t("workspace.routingRules.copy.of"),
	entries: i18n.t("workspace.routingRules.copy.entries"),
	deleteRule: i18n.t("workspace.routingRules.copy.deleteRule"),
	deleteRuleConfirm: (name: string) => i18n.t("workspace.routingRules.copy.deleteRuleConfirm", { value0: name }),
	deleting: i18n.t("workspace.routingRules.copy.deleting"),
	moreTargets: (count: number) => i18n.t("workspace.routingRules.copy.moreTargets", { count }),
	any: i18n.t("workspace.routingRules.copy.any"),
	anyModel: i18n.t("workspace.routingRules.copy.anyModel"),
	pageSummary: (start: number, end: number, total: number) =>
		i18n.t("workspace.routingRules.copy.pageSummary", { value0: start, value1: end, value2: total }),
	manageDescription: i18n.t("workspace.routingRules.copy.manageDescription"),
	viewTreeTitle: i18n.t("workspace.routingRules.copy.viewTreeTitle"),
	viewTree: i18n.t("workspace.routingRules.copy.viewTree"),
	newRuleTitle: i18n.t("workspace.routingRules.copy.newRuleTitle"),
	ruleCount: (count: number) => i18n.t("workspace.routingRules.copy.ruleCount", { count }),
	targetCount: (count: number) => i18n.t("workspace.routingRules.copy.targetCount", { count }),
	scopeLabel: (scope: string) =>
		({
			global: i18n.t("workspace.routingRules.copy.scopeLabel_global"),
			team: i18n.t("workspace.routingRules.copy.scopeLabel_team"),
			customer: i18n.t("workspace.routingRules.copy.scopeLabel_customer"),
			virtual_key: i18n.t("workspace.routingRules.copy.scopeLabel_virtual_key"),
			user: i18n.t("workspace.routingRules.copy.scopeLabel_user"),
		})[scope] ?? scope,
};