const content = {
	en: {
		routingRuleStats: "Routing rule requests",
		routingRuleStatsDescription: "Request outcomes attributed to each routing rule in the selected period.",
		routingRuleStatsError: "Routing rule statistics could not be loaded.",
		noRoutingRuleStats: "No routed requests in this period.",
		routingRule: "Routing rule",
		requests: "Requests",
		successful: "Successful",
		failed: "Failed",
		requestVolume: "Request volume",
		total: "Total",
		success: "Success",
		error: "Error",
		cancelled: "Cancelled",
		tokenUsage: "Token usage",
		input: "Input",
		output: "Output",
		cached: "Cached",
		externalCacheHitRate: "External cache hit rate",
		localCacheHitRate: "Local cache hit rate",
		cost: "Cost",
		modelUsage: "Model usage",
		latency: "Latency",
		average: "Avg",
		bifrostOverhead: "Bifrost overhead",
		throughput: "Throughput",
		tokensPerSecond: "Tokens/sec",
		more: (count: number) => `+${count} more`,
	},
	zh: {
		routingRuleStats: "路由规则请求统计",
		routingRuleStatsDescription: "所选时间范围内归属于各路由规则的请求结果。",
		routingRuleStatsError: "无法加载路由规则统计。",
		noRoutingRuleStats: "该时间范围内没有路由请求。",
		routingRule: "路由规则",
		requests: "请求数",
		successful: "成功",
		failed: "失败",
		requestVolume: "请求量",
		total: "总计",
		success: "成功",
		error: "错误",
		cancelled: "已取消",
		tokenUsage: "Token 使用量",
		input: "输入",
		output: "输出",
		cached: "缓存",
		externalCacheHitRate: "外部缓存命中率",
		localCacheHitRate: "本地缓存命中率",
		cost: "成本",
		modelUsage: "模型使用量",
		latency: "延迟",
		average: "平均",
		bifrostOverhead: "Bifrost 开销",
		throughput: "吞吐量",
		tokensPerSecond: "Tokens/秒",
		more: (count: number) => `另有 ${count} 项`,
	},
} as const;

export function dashboardCopy() {
	return typeof document !== "undefined" && document.documentElement.lang.toLowerCase().startsWith("zh") ? content.zh : content.en;
}